(function () {
  const extra = [];
  function Q(category, q, options, correct, expl) {
    extra.push({
      id: "px-" + extra.length,
      category: category,
      q: q,
      options: options,
      correct: correct,
      expl: expl
    });
  }

  /* ABS */
  Q("abs", "Sur route mouillée, freinage d'urgence : l'ABS permet surtout de", ["Garder la trajectoire en limitant le blocage", "Supprimer totalement la distance d'arrêt", "Remplacer le frein de parc", "Couper l'alimentation air"], 0, "L'ABS limite le blocage pour conserver la direction ; il ne garantit pas une distance plus courte sur sol glissant.");
  Q("abs", "Le modulateur ABS agit en modifiant", ["La pression de freinage par roue ou essieu", "Le débit carburant injecté", "La pression des pneus", "Le rapport de pont"], 0, "Le modulateur relâche ou reprend la pression de frein sur la roue qui décélère trop vite.");
  Q("abs", "Un capteur ABS mesure principalement", ["La vitesse de rotation de la roue", "La température du liquide de refroidissement", "Le niveau AdBlue", "La charge utile"], 0, "La vitesse de roue permet de détecter un début de blocage.");
  Q("abs", "Voyant ABS allumé en roulant : conduite à adopter", ["Freiner plus tôt et faire contrôler le système", "Couper le moteur immédiatement", "Utiliser uniquement le frein de parc", "Augmenter la vitesse pour réinitialiser"], 0, "L'antiblocage peut être indisponible ; les freins de service restent actifs mais les roues peuvent bloquer.");
  Q("abs", "Lors d'une intervention ABS, la pédale peut", ["Vibrer ou pulser : comportement normal", "Devenir inutilisable définitivement", "Serrer le frein de stationnement", "Couper le régulateur de vitesse"], 0, "Les pulsations traduisent le cycle serrage-relâchement ; il faut maintenir la pression.");
  Q("abs", "L'ABS intervient typiquement lorsque", ["Une roue risque de se bloquer au freinage", "Le moteur dépasse le régime maxi", "La remorque est dételée", "Le PTAC est dépassé"], 0, "L'ABS réagit au risque de blocage, pas à la masse ou au régime moteur.");
  Q("abs", "Sur neige compactée, l'ABS peut parfois", ["Allonger légèrement la distance d'arrêt tout en gardant le contrôle", "Désactiver le freinage arrière", "Bloquer volontairement les roues avant", "Remplacer les ralentisseurs"], 0, "Un léger blocage peut parfois mieux mordre sur meuble ; l'ABS privilégie le contrôle directionnel.");
  Q("abs", "En urgence avec ABS, la bonne conduite est", ["Appuyer fort et maintenir sans pomper", "Pomper la pédale comme sans ABS", "Relâcher dès les pulsations", "Tirer le frein de parc en premier"], 0, "L'ABS gère les cycles ; le conducteur maintient une pression forte et constante.");
  Q("abs", "L'ABS ne remplace pas", ["L'anticipation et la distance de sécurité", "Les essieux arrière", "La carte grise", "Le permis C"], 0, "L'énergie cinétique dépend de la masse et de la vitesse ; l'ABS n'augmente pas l'adhérence.");
  Q("abs", "Quel composant n appartient pas à la chaîne ABS ?", ["Vanne EGR", "Calculateur ABS", "Capteur de roue", "Électrovanne modulatrice"], 0, "La vanne EGR recycle les gaz d'échappement pour limiter les NOx.");
  Q("abs", "Au contact, voyant ABS puis extinction rapide :", ["Autotest normal fréquent", "Panne confirmée obligatoire", "Signe de surcharge essieu", "Désactivation permanente ESP"], 0, "Beaucoup de véhicules testent l'ABS à la mise du contact.");
  Q("abs", "Sur PL, l'ABS surveille en général", ["Chaque roue ou chaque essieu selon architecture", "Uniquement l'essieu directeur", "Seulement la remorque", "Uniquement au-dessus de 90 km/h"], 0, "Les capteurs sont placés sur les roues freinées du tracteur et souvent de la remorque.");
  Q("abs", "Freinage fort sur sol sec avec ABS : on peut", ["Corriger la trajectoire tout en freinant", "Jamais braquer", "Uniquement si ASR actif", "Seulement en descente"], 0, "L'intérêt principal est de freiner fort sans perdre la direction.");
  Q("abs", "Si une roue se bloque sans ABS", ["Elle glisse et la direction est perdue", "Le véhicule accélère", "Le PTAC diminue", "L'ESP compense automatiquement"], 0, "Roue bloquée = plus de guidage par le pneu concerné.");
  Q("abs", "L'ABS agit sur le freinage de", ["Service (pédale)", "Stationnement ressorts", "Uniquement le moteur", "Uniquement l'embrayage"], 0, "L'ABS module le frein de service, pas le frein de parc à ressorts.");
  Q("abs", "Une panne ABS signifie", ["Freins de service possibles mais sans antiblocage", "Plus aucun freinage possible", "Obligation de rouler à 30 km/h maxi", "Désactivation automatique du moteur"], 0, "Le circuit pneumatique de service reste en principe opérationnel.");
  Q("abs", "L'ABS réduit surtout le risque de", ["Dérapage directionnel par blocage", "Surcharge PTAC", "Usure embrayage", "Pollution NOx"], 0, "Objectif : garder la capacité de braquer en urgence.");
  Q("abs", "Sur route verglacée, avec ABS", ["On adapte vitesse et distance malgré l'ABS", "On peut coller le véhicule devant", "Le frein de parc suffit en descente", "L'ABS supprime l'aquaplaning"], 0, "L'ABS ne crée pas d'adhérence supplémentaire sur glace.");
  Q("abs", "Le calculateur ABS reçoit des informations de", ["Capteurs de vitesse de roue", "Capteurs de niveau carburant uniquement", "Jauge de charge utile", "Capteur de hauteur seulement"], 0, "La décision repose sur la comparaison des vitesses de rotation des roues.");
  Q("abs", "Relâcher la pédale à chaque pulsation ABS", ["Diminue l'efficacité du système", "Est la technique recommandée", "Active le frein de parc", "Coupe l'EBS"], 0, "Il faut laisser l'ABS moduler sans pomper.");
  Q("abs", "L'ABS est complémentaire de", ["EBS et ESP sur véhicules récents", "La vanne EGR seule", "Le ralentisseur moteur seul", "Le contrôle technique remorque seul"], 0, "L'EBS intègre souvent ABS ; l'ESP s'appuie aussi sur les capteurs de roue.");
  Q("abs", "Remorque ABS défaillante sur attelage", ["Peut freiner moins harmonieusement : prudence", "Annule le PTAC tracteur", "Bloque le différentiel", "Coupe l'AFU tracteur"], 0, "La coordination tracteur-remorque est essentielle au freinage harmonieux.");
  /* EBS */
  Q("ebs", "EBS signifie", ["Electronic Braking System : freinage à commande électronique", "Emergency Brake Stop : arrêt d'urgence mécanique", "Engine Boost Sensor : capteur suralimentation", "Empty Brake Supply : réserve air vide"], 0, "L'EBS commande le freinage par signaux électriques vers un calculateur.");
  Q("ebs", "Dans l'EBS, l'air comprimé sert surtout à", ["Serrer les freins (énergie de freinage)", "Alimenter la radio", "Mesurer le PTAC", "Recycler les gaz EGR"], 0, "Électronique = commande ; air = muscle des freins.");
  Q("ebs", "Avantage majeur EBS vs circuit 100 % pneumatique", ["Réponse plus rapide et répartition affinée", "Suppression totale de l'air", "Plus de frein de parc", "PTAC augmenté automatiquement"], 0, "Le signal électrique est quasi immédiat, surtout vers la remorque.");
  Q("ebs", "Pan électronique EBS : mode secours", ["Freinage pneumatique de secours possible", "Aucun freinage possible", "Frein de parc se serre à 80 km/h", "Moteur calé obligatoire"], 0, "Un repli pneumatique permet encore de s arrêter.");
  Q("ebs", "L'EBS intègre généralement", ["ABS et parfois ASR ou ESP", "Uniquement la climatisation", "La vanne EGR seule", "Le hayon élévateur"], 0, "L'EBS est un système global de freinage électronique.");
  Q("ebs", "La prise EBS remorque sert à", ["Synchroniser freinage tracteur et semi", "Gonfler les pneus remorque", "Alimenter le frigo uniquement", "Mesurer la longueur 16,50 m"], 0, "Sans liaison, la remorque peut freiner moins finement.");
  Q("ebs", "Le calculateur EBS utilise notamment", ["Pression pédale, vitesses roues, charges", "Couleur de la cabine", "Numéro de permis", "Volume AdBlue seul"], 0, "Il dose le freinage selon l'état dynamique du véhicule.");
  Q("ebs", "Sur longue descente, l'EBS peut", ["Coordonner frein service et ralentisseur selon véhicule", "Interdire tout ralentisseur", "Vider les réservoirs d'air", "Augmenter le régime moteur seul"], 0, "La coordination limite la surchauffe des tambours.");
  Q("ebs", "Freinage EBS sur sol sec : répartition", ["Peut favoriser un équilibre AV/AR optimisé", "Toujours 100 % arrière", "Uniquement avant", "Aléatoire"], 0, "Le calculateur adapte la répartition à la charge et à l'adhérence.");
  Q("ebs", "Voyant EBS allumé", ["Réduire la vitesse et faire contrôler", "Continuer normalement sans limite", "Couper l'ABS volontairement", "Augmenter la pression des pneus"], 0, "Des fonctions électroniques peuvent être dégradées.");
  Q("ebs", "L'EBS réduit surtout", ["Les à-coups et retards de freinage remorque", "La consommation carburant directement", "La hauteur du véhicule", "Le PTAC légal"], 0, "Meilleure harmonisation tracteur-remorque.");
  Q("ebs", "Capteur de pression de freinage EBS", ["Informe le calculateur sur l'effort demandé", "Mesure la température EGR", "Contrôle la largeur 2,55 m", "Remplace le tachymètre"], 0, "La pédale envoie une demande de freinage au calculateur.");
  Q("ebs", "EBS et ABS : relation", ["L'EBS inclut souvent l'ABS", "L'ABS remplace entièrement l'EBS", "Aucun lien possible", "L'EBS supprime l'air"], 0, "L'ABS est une fonction ; l'EBS est le système complet.");
  Q("ebs", "Sur attelage, EBS HS côté remorque", ["Freinage moins performant possible : prudence", "PTAC tracteur annulé", "ESP désactivé automatiquement", "Frein de parc se desserre"], 0, "La semi peut repasser en freinage classique moins fin.");
  Q("ebs", "Modulateur EBS sur essieu", ["Dose la pression de frein de cet essieu", "Régule la vitesse moteur", "Contrôle la vanne EGR", "Mesure la CU"], 0, "Chaque essieu peut recevoir une pression adaptée.");
  Q("ebs", "L'EBS améliore surtout", ["La stabilité de freinage de l'ensemble", "La vitesse maximale autorisée", "La longueur légale", "Le nombre d'essieux"], 0, "Objectif : freiner l'ensemble de façon cohérente.");
  Q("ebs", "Signal pédale EBS", ["Électrique vers calculateur", "100 % mécanique sans capteur", "Hydraulique uniquement sur PL", "Radio HF"], 0, "La demande de freinage est traitée électroniquement.");
  Q("ebs", "Contrôle EBS au branchement remorque", ["Vérifier prise et voyants avant départ", "Ignorer si ABS tracteur OK", "Uniquement en hiver", "Seulement au-delà de 40 t"], 0, "La liaison électronique conditionne la performance.");
  Q("ebs", "EBS en urgence", ["Peut appliquer vite une forte décélération coordonnée", "Coupe le freinage arrière", "Desserre le frein de parc", "Bloque le différentiel"], 0, "La rapidité de commande aide en urgence.");
  Q("ebs", "Maintenance EBS", ["Diagnostic électronique spécialisé", "Vidange huile moteur seule", "Gonflage pneus 3 bar partout", "Réglage EGR manuel"], 0, "Système complexe nécessitant outils adaptés.");
  Q("ebs", "EBS ne remplace pas", ["L'entretien des tambours et mâchoires", "Le permis C", "La ceinture de sécurité", "Toutes les réponses"], 3, "L'EBS optimise la commande ; l'usure mécanique reste à surveiller.");
  Q("ebs", "Sur porteur 2 essieux, EBS avant/arrière", ["Peut moduler séparément selon charge", "Freine uniquement l'essieu moteur", "Désactive l'ASR", "Fixe le PTAC à 32 t"], 0, "La charge sur essieu directeur et porteur varie selon chargement.");
  /* ESP */
  Q("esp", "ESP signifie sur PL", ["Electronic Stability Program : contrôle de trajectoire", "Engine Speed Pilot : limiteur moteur", "Emergency Stop Procedure : arrêt park", "Empty Storage Pressure : air réservoir"], 0, "L'ESP corrige les trajectoires en limite d'adhérence.");
  Q("esp", "L'ESP intervient surtout quand", ["Le véhicule part en sous-virage ou survirage", "Le réservoir AdBlue est plein", "Le PTAC est exact", "Le moteur est au ralenti"], 0, "Il détecte une trajectoire différente de la direction demandée.");
  Q("esp", "Pour corriger, l'ESP peut", ["Freiner une roue et réduire le couple moteur", "Augmenter la pression des pneus", "Serrer le frein de parc", "Ouvrir la vanne EGR"], 0, "Freinage sélectif et gestion moteur stabilisent le véhicule.");
  Q("esp", "ESP et ABS : lien", ["L'ESP s'appuie sur capteurs roues et ABS", "L'ESP remplace l'ABS", "Sans lien", "L'ESP coupe l'ABS"], 0, "Les capteurs de vitesse de roue servent aux deux systèmes.");
  Q("esp", "Sur citerne partiellement remplie, l'ESP est", ["Particulièrement utile (ballotement)", "Inutile car PTAC bas", "Interdit", "Réservé au 44 t"], 0, "Centre de gravité haut et liquide mobile augmentent le risque de tonneau.");
  Q("esp", "Voyant ESP clignotant en virage serré", ["Intervention normale du système", "Panne obligatoire immédiate", "Surcharge PTAC", "Défaut EGR"], 0, "Le clignotement signale une correction en cours.");
  Q("esp", "Conduite avec ESP : le conducteur doit", ["Adapter vitesse surtout sur chargements instables", "Augmenter la vitesse en virage", "Couper l'ABS", "Utiliser le frein de parc en courbe"], 0, "L'ESP aide mais ne supprime pas la physique du chargement.");
  Q("esp", "L'ESP ne corrige pas", ["Une vitesse excessive en entrée de virage", "Un léger sous-virage modéré", "Un survirage léger", "Une différence de vitesse roues"], 0, "Au-delà des limites d'adhérence, aucun système ne sauve tout.");
  Q("esp", "Capteur de lacet ESP", ["Mesure la rotation autour de l'axe vertical", "Mesure le PTAC", "Contrôle la température frein", "Régule l'EGR"], 0, "Il détecte une rotation non voulue du véhicule.");
  Q("esp", "Sur sol glissant, ESP + ABS", ["Aident à garder le contrôle sans créer d'adhérence", "Permettent de rouler à vitesse normale", "Remplacent les chaînes", "Augmentent le PTRA"], 0, "Les aides électroniques ne remplacent pas l'anticipation.");
  Q("esp", "ESP sur remorque (selon équipement)", ["Peut inclure stabilisation remorque", "Impossible techniquement", "Remplace le contrôle PTAC", "Coupe le ralentisseur moteur"], 0, "Certains ensembles intègrent ESP remorque.");
  Q("esp", "Désactiver l'ESP sur route mouillée", ["Augmente le risque de perte de contrôle", "Améliore toujours l'adhérence", "Est obligatoire FIMO", "Réduit la consommation"], 0, "L'ESP est une aide de sécurité active.");
  Q("esp", "ESP et ASR : différence", ["ESP = trajectoire ; ASR = patinage à l'accélération", "Identiques", "ESP = frein de parc", "ASR = trajectoire"], 0, "Deux fonctions complémentaires de stabilité.");
  Q("esp", "Freinage fort en courbe : l'ESP", ["Peut freiner une roue pour redresser", "Desserre les freins avant", "Active le frein de parc", "Coupe l'alimentation air"], 0, "Correction par freinage sélectif.");
  Q("esp", "Sur bétaillère, l'ESP", ["Limite le risque de renversement", "Augmente la CU", "Modifie le PTAC carte grise", "Remplace la ceinture"], 0, "Haut centre de gravité = risque de tonneau accru.");
  Q("esp", "Calculateur ESP utilise", ["Direction, lacet, vitesses roues, accélérations", "Uniquement la vitesse GPS", "Couleur remorque", "Pression pneus seule"], 0, "Analyse multi-capteurs de la trajectoire réelle.");
  Q("esp", "ESP en ligne droite sur autoroute", ["Intervient peu si trajectoire stable", "Freine en permanence", "Coupe le moteur", "Serre le frein de parc"], 0, "Pas d'écart de trajectoire = pas de correction.");
  Q("esp", "Panne ESP : conduite", ["Prudence accrue en virage et sur sol glissant", "Conduite identique à 130 km/h", "Plus de frein service", "PTAC réduit de moitié"], 0, "Perte d'aide à la stabilité dynamique.");
  Q("esp", "ESP et charge mal arrimée", ["Ne compense pas un chargement dangereux", "Corrige tout déplacement interne", "Bloque la marchandise", "Augmente le PTAC"], 0, "Arrimage correct reste obligatoire.");
  Q("esp", "Survirage en PL : l'ESP peut", ["Freiner roue intérieure avant pour redresser", "Accélérer toutes les roues", "Ouvrir le frein de parc", "Couper l'EBS totalement"], 0, "Freinage ciblé pour réduire la rotation excessive.");
  Q("esp", "Sous-virage : l'ESP peut", ["Freiner roue arrière intérieure", "Augmenter le régime moteur maxi", "Desserrer le frein de parc", "Modifier le PTRA"], 0, "Aide à pivoter le véhicule vers la trajectoire voulue.");
  Q("esp", "Message ESP off sur tableau de bord", ["Système désactivé ou en défaut : vigilance", "Gain de vitesse autorisé", "PTAC augmenté", "Freinage automatique coupé"], 0, "Vérifier cause : bouton off ou anomalie.");
  /* CHAINE */
  Q("chaine", "La chaîne cinématique d'un PL comprend", ["Moteur, embrayage, boîte, pont, roues", "Uniquement freins et ABS", "EGR et AdBlue seulement", "Régulateur et GPS"], 0, "Transmission de la puissance moteur aux roues motrices.");
  Q("chaine", "Le pont ( différentiel ) sert à", ["Transmettre le couple aux roues avec démultiplication", "Freiner le véhicule", "Recycler les gaz", "Mesurer le PTAC"], 0, "Dernier réducteur avant les roues motrices.");
  Q("chaine", "Boîte de vitesses sur PL : rôle", ["Adapter régime moteur et couple à la charge", "Contrôler l'ESP", "Régler le PTAC", "Alimenter le frein de parc"], 0, "Choix du rapport selon pente, charge et vitesse.");
  Q("chaine", "Embrayage usé : conséquence fréquente", ["Patins et difficulté à démarrer chargé", "ABS défaillant", "PTAC diminué", "EGR bloquée"], 0, "Glissement = chaleur et usure accélérée.");
  Q("chaine", "Blocage différentiel : usage principal", ["Terrain glissant où une roue patine", "Virage sec autoroute", "Freinage d'urgence", "Contrôle PTAC"], 0, "Égalise le couple quand'une roue perd adhérence.");
  Q("chaine", "Blocage diff en virage sec", ["Risque d'usure et de contrainte mécanique", "Recommandé systématiquement", "Active l'ESP", "Augmente le PTAC"], 0, "En virage les roues parcourent des distances différentes.");
  Q("chaine", "Overdrive en boîte", ["Rapport surmultiplié pour économiser à vitesse stabilisée", "Frein moteur maximal", "Mode parking", "Réglage EGR"], 0, "Régime moteur plus bas à vitesse de croisière.");
  Q("chaine", "Rapport de pont élevé (court)", ["Plus de couple roues, moins de vitesse maxi", "Moins de couple, plus de vitesse", "Coupe l'ASR", "Modifie le PTRA"], 0, "Pont court = favorise démarrage et côtes.");
  Q("chaine", "Boîte automatisée (robotisée)", ["Embrayage et levées gérés électroniquement", "Supprime le pont", "Remplace le frein service", "Mesure la surcharge"], 0, "Automatisation des commandes sans supprimer la mécanique.");
  Q("chaine", "Frein moteur par rétrogradation", ["Augmente le freinage par compression", "Coupe l'alimentation carburant totale", "Serre le frein de parc", "Active l'AFU"], 0, "Rapport plus court = régime plus haut = frein moteur plus fort.");
  Q("chaine", "Prise de force ( PTO ) sert à", ["Entraîner un équipement auxiliaire", "Freiner la remorque", "Contrôler l'ABS", "Mesurer la CU"], 0, "Exemple : pompe hayon ou grue.");
  Q("chaine", "Arbre de transmission cardan", ["Relie boîte ou pont intermédiaire au pont", "Mesure la vitesse ESP", "Alimente l'EGR", "Contrôle le PTAC"], 0, "Transmet le couple avec angles variables.");
  Q("chaine", "Synchroniseurs en boîte manuelle", ["Facilitent le passage de vitesses", "Freinent le véhicule", "Contrôlent l'ASR", "Régulent la pression air"], 0, "Évitent le grincement à l'embrayage.");
  Q("chaine", "Couple moteur maximal : en pratique", ["Disponible sur une plage de régime", "À 500 tr/min seulement", "Uniquement à l'arrêt", "Indépendant du rapport"], 0, "Courbe couple/régime : zone optimale à connaître.");
  Q("chaine", "Chaîne cinématique et conso : levier", ["Choisir le bon rapport évite sur-régime", "Rouler en sous-régime lourd consomme plus", "Les deux réponses précédentes", "Couper l'ESP réduit la conso"], 2, "Bon rapport = moteur ni trop haut ni trop bas.");
  Q("chaine", "Pont relevable ( relevage essieu )", ["Réduit résistance roulement à vide", "Augmente le PTAC carte grise", "Coupe l'ABS", "Remplace le frein de parc"], 0, "Essieu relevé hors charge pour économiser.");
  Q("chaine", "Transmission intégrale sur PL ( rare )", ["Peut motiver plusieurs essieux", "Supprime le différentiel", "Interdit en France", "Remplace le PTRA"], 0, "Plusieurs essieux recevant le couple moteur.");
  Q("chaine", "Usure boîte : signe courant", ["Sauts ou bruits au passage des vitesses", "Voyant ABS permanent", "EGR ouverte", "Frein de parc desserré"], 0, "Synchronisation ou commande défectueuse.");
  Q("chaine", "Double embrayage ( selon modèles )", ["Permet des changements rapides", "Remplace le frein service", "Mesure la surcharge", "Contrôle la vanne EGR"], 0, "Technologie de boîte automatisée performante.");
  Q("chaine", "Ne pas forcer un rapport inadapté en côte", ["Risque de calage et d'usure embrayage", "Améliore l'ABS", "Augmente le PTAC", "Active l'ESP automatiquement"], 0, "Adapter le rapport à la pente et à la masse.");
  Q("chaine", "Chaîne cinématique et freinage", ["Le frein moteur complète freins service et ralentisseurs", "Le frein moteur remplace le frein de parc", "L'embrayage serre les tambours", "Le pont active l'AFU"], 0, "Complémentarité des moyens de décélération.");
  Q("chaine", "Maintenance chaîne : niveau important", ["Huile pont et boîte selon constructeur", "Pression pneus uniquement", "Réglage EGR manuel", "Gonflage air frein park"], 0, "Lubrification vitale pour durée de vie.");
  /* AFU */
  Q("afu", "AFU signifie", ["Amplificateur de Freinage d Urgence", "Assistant de Freinage Urbain", "Alimentation Frein Unifiée", "Antipatinage Frein Usure"], 0, "L'AFU détecte un freinage d'urgence insuffisant et amplifie la pression.");
  Q("afu", "L'AFU intervient quand", ["La pédale est enfoncée vite mais pas assez fort", "On freine doucement au feu rouge", "On utilise le frein de parc", "Le moteur est au ralenti"], 0, "Piège FIMO : ce n est pas un freinage confortable.");
  Q("afu", "L'AFU ne remplace pas", ["La décision et la force du conducteur", "Les tambours usés", "Le permis C", "Toutes les réponses"], 3, "Aide en urgence mais le conducteur doit freiner fort.");
  Q("afu", "Capteur AFU mesure surtout", ["Vitesse et course de la pédale", "Température EGR", "PTAC remorque", "Largeur 2,55 m"], 0, "Une montée rapide de pédale signale une urgence.");
  Q("afu", "Freinage progressif au feu : AFU", ["N'intervient généralement pas", "Amplifie toujours à fond", "Serre le frein de parc", "Coupe le moteur"], 0, "Pas une urgence = pas d'amplification.");
  Q("afu", "AFU et ABS : relation", ["Complémentaires sur freinage d'urgence", "L'AFU remplace l'ABS", "Sans lien", "L'AFU bloque l'ABS"], 0, "AFU = force ; ABS = antiblocage.");
  Q("afu", "Conducteur hésitant en urgence : AFU", ["Peut compenser partiellement une pression trop faible", "Roule à sa place", "Coupe l'ESP", "Modifie le PTRA"], 0, "Amplification si la demande est trop faible pour le danger.");
  Q("afu", "AFU ne détecte pas", ["Une urgence si la pédale reste molle et lente", "Une montée rapide de pédale", "Une forte demande de décélération", "Une vitesse élevée seule"], 0, "Il faut une action rapide et déterminée sur la pédale.");
  Q("afu", "Panne AFU : conséquence", ["Freinage d'urgence sans amplification possible", "Plus de frein service", "PTAC réduit", "ABS coupé"], 0, "Les freins restent ; seule l'aide d'urgence manque.");
  Q("afu", "AFU sur PL récent", ["Souvent intégré au système EBS", "100 % mécanique sans capteur", "Remplace le ralentisseur", "Contrôle la vanne EGR"], 0, "Fait partie de l'électronique embarquée freinage.");
  Q("afu", "En urgence, bon réflexe avec AFU", ["Appuyer fort, vite et maintenir", "Tapoter la pédale", "Utiliser le frein de parc d'abord", "Couper le contact"], 0, "L'AFU aide mais ne dispense pas d'appuyer fort.");
  Q("afu", "AFU et frein de parc", ["Sans relation directe", "L'AFU serre le park", "Le park active l'AFU", "Identiques"], 0, "Deux systèmes distincts.");
  Q("afu", "Vitesse élevée + obstacle : AFU", ["Peut aider à atteindre décélération maximale plus vite", "Réduit la distance automatiquement à zéro", "Coupe l'ASR seulement", "Augmente le PTAC"], 0, "Réduit le temps pour atteindre pleine pression.");
  Q("afu", "AFU ≠ ESP", ["Vrai : rôles différents", "Faux : identiques", "L'ESP amplifie la pédale", "L'AFU corrige la trajectoire"], 0, "AFU = urgence frein ; ESP = stabilité trajectoire.");
  Q("afu", "Conducteur qui freine à mi-course en urgence", ["L'AFU peut renforcer la pression", "Rien ne se passe", "Frein de parc se desserre", "EGR s ouvre"], 0, "Typique cas d'intervention AFU.");
  Q("afu", "Entretien AFU", ["Lié au système de freinage électronique", "Vidange pont uniquement", "Réglage phares", "Gonflage 9 bar park"], 0, "Diagnostic via calculateur freinage.");
  Q("afu", "AFU en côte descendante", ["N remplace pas ralentisseur et frein service", "Remplace tous les freins", "Coupe l'EBS", "Désactive l'ABS"], 0, "Descente longue = combinaison des moyens.");
  Q("afu", "Capteur pédale AFU défaillant", ["AFU peut être indisponible", "Plus de freinage possible", "PTRA à 26 t", "ESP forcé off"], 0, "Frein service reste ; amplification absente.");
  Q("afu", "AFU et charge lourde", ["Urgence nécessite toujours plus de distance malgré AFU", "Distance identique à vide", "PTAC annulé", "ABS inutile"], 0, "Masse élevée = plus d'énergie à dissiper.");
  Q("afu", "Message AFU au tableau de bord", ["Faire contrôler le système freinage", "Continuer sans limite", "Couper l'ASR", "Relever essieu"], 0, "Défaut = perte d'aide urgence.");
  Q("afu", "AFU déclenché : ressenti possible", ["Montée brusque de l'effort de freinage", "Desserrage frein de parc", "Accélération moteur", "Ouverture EGR"], 0, "Le conducteur sent une amplification nette.");
  Q("afu", "En FIMO, l'AFU est présenté comme", ["Amplificateur si urgence mal assumée", "Frein automatique permanent", "Régulateur de vitesse", "Contrôle PTAC"], 0, "Piège : pas un régulateur, pas un frein seul.");
  /* EGR */
  Q("egr", "La vanne EGR sert à", ["Recycler une partie des gaz d'échappement vers admission", "Freiner le véhicule", "Contrôler l'ABS", "Mesurer le PTAC"], 0, "Recirculation pour baisser température combustion et NOx.");
  Q("egr", "EGR et pollution : objectif principal", ["Réduire les oxydes d'azote ( NOx )", "Augmenter les particules volontairement", "Couper le CO2 totalement", "Remplacer l AdBlue"], 0, "NOx diminue si combustion moins chaude.");
  Q("egr", "EGR ouverte en charge faible", ["Comportement normal pour limiter NOx", "Panne systématique", "Signe de surcharge", "Frein de parc desserré"], 0, "Fonctionnement fréquent à faible charge.");
  Q("egr", "Vanne EGR encrassée : risque", ["Perte puissance et mode dégradé moteur", "ABS coupé", "PTAC augmenté", "ESP renforcé"], 0, "Encrassement fréquent sur usage urbain.");
  Q("egr", "EGR ≠ AdBlue", ["Vrai : deux systèmes distincts", "Faux : identiques", "L AdBlue remplace l'EGR", "L'EGR mesure la CU"], 0, "EGR = recirculation ; SCR/AdBlue = traitement NOx aval.");
  Q("egr", "Défaut EGR : voyant moteur", ["Faire diagnostiquer, ne pas forcer", "Continuer à fond longtemps", "Couper l'ABS", "Augmenter le PTAC"], 0, "Mode dégradé possible avec couple limité.");
  Q("egr", "EGR et température moteur", ["Refroidit la combustion en diluant le mélange", "Augmente toujours la température", "Coupe le turbo", "Serre le frein de parc"], 0, "Gaz inertes abaissent pic de température.");
  Q("egr", "Maintenance EGR préventive", ["Nettoyage ou remplacement selon usage", "Ignorer jusqu à casse moteur", "Gonflage pneus", "Réglage frein park"], 0, "Entretien régulier sur cycles urbains.");
  Q("egr", "EGR ne concerne pas", ["Le circuit de freinage ABS", "Les émissions moteur", "La vanne d'admission", "Le calculateur moteur"], 0, "Système antipollution moteur.");
  Q("egr", "Conduite urbaine stop-and-go et EGR", ["Encrassement plus rapide possible", "EGR jamais sollicitée", "PTAC modifié", "ESP désactivé"], 0, "Faibles régimes favorisent les dépôts.");
  Q("egr", "EGR fermée à pleine charge", ["Possible selon stratégie moteur", "Impossible techniquement", "Obligatoire permanente", "Coupe le freinage"], 0, "Priorité puissance : EGR peut se fermer.");
  Q("egr", "Symptôme EGR bloquée ouverte", ["Calages, fumée, perte de reprise", "Freinage renforcé", "ABS permanent", "PTRA 44 t automatique"], 0, "Mélange admission perturbé.");
  Q("egr", "EGR et Euro 6", ["Intégrée à stratégie globale antipollution", "Interdite", "Remplace le catalyseur seul", "Mesure la largeur"], 0, "Combinée SCR, DPF, etc.");
  Q("egr", "Capteur position vanne EGR", ["Informe le calculateur sur l'ouverture", "Mesure vitesse roue", "Contrôle frein park", "Calcule PTRA"], 0, "Régulation boucle fermée.");
  Q("egr", "Forcer conduite avec défaut EGR", ["Risque casse et verbalisation", "Recommandé FIMO", "Améliore l'ABS", "Augmente la CU"], 0, "Respecter mode dégradé et réparation.");
  Q("egr", "EGR refroidisseur ( EGR cooler )", ["Baisse température gaz recyclés", "Chauffe les freins", "Contrôle l'ESP", "Mesure PTAC"], 0, "Gaz plus froids = meilleure efficacité NOx.");
  Q("egr", "Débrancher EGR illégalement", ["Interdit et contrôle technique compromis", "Autorisé FIMO", "Améliore légalité", "Augmente PTRA"], 0, "Tricherie antipollution sanctionnée.");
  Q("egr", "EGR et ralenti instable", ["Peut être un indice de vanne sale", "Signe ABS HS", "PTAC dépassé", "Frein park desserré"], 0, "Diagnostic moteur nécessaire.");
  Q("egr", "Relation EGR et consommation", ["EGR bien gérée peut aider l'efficacité", "Double toujours la conso", "Sans effet", "Coupe l'ASR"], 0, "Optimisation moteur globale.");
  Q("egr", "Voyant pollution + perte puissance", ["Penser EGR, DPF ou SCR selon diagnostic", "Ignorer", "Couper ESP", "Relever essieu"], 0, "Plusieurs systèmes Euro 6 liés.");
  Q("egr", "EGR : piège FIMO fréquent", ["Agit sur gaz échappement, pas sur freins", "Remplace l'AFU", "Contrôle trajectoire", "Serre frein service"], 0, "Ne pas confondre avec ABS/ESP/AFU.");
  Q("egr", "Après longue marche urbaine, EGR", ["Vérifier entretien préventif planifié", "Jamais entretenue", "Remplace contrôle PTAC", "Modifie essieux"], 0, "Usage ville = maintenance EGR importante.");
  /* RALENTISSEURS */
  Q("ralentisseurs", "Combien de types de ralentisseurs au FIMO PL ?", ["Quatre : moteur, échappement, hydrodynamique, électromagnétique", "Deux : ABS et ESP", "Un seul : frein de parc", "Trois : air, huile, eau"], 0, "Les quatre familles sont au programme FIMO.");
  Q("ralentisseurs", "Ralentisseur moteur : principe", ["Freinage par compression et pertes moteur", "Serre tambours service", "Desserre frein de parc", "Recycle gaz EGR"], 0, "Régime moteur élevé en rapport bas = frein moteur.");
  Q("ralentisseurs", "Ralentisseur échappement ( VEB )", ["Crée contre-pression dans l'échappement", "Gonfle les pneus", "Contrôle l'ESP", "Mesure PTAC"], 0, "Vanette d'échappement augmentant la contre-pression.");
  Q("ralentisseurs", "Ralentisseur hydrodynamique", ["Utilise un fluide et un stator ( retarder )", "Frein à disque classique", "Remplace embrayage", "Mesure PTRA"], 0, "Souvent sur prise de force ou arbre transmission.");
  Q("ralentisseurs", "Ralentisseur électromagnétique", ["Fretage électromagnétique ( champ )", "Pompe hydraulique frein park", "Vanne EGR", "Capteur ABS"], 0, "Fonctionne par induction sur arbre ou disque.");
  Q("ralentisseurs", "En descente longue, priorité FIMO", ["Ralentisseur puis frein service par intermittence", "Frein service continu seul", "Frein de parc", "Couper moteur"], 0, "Préserver freins service = éviter fade thermique.");
  Q("ralentisseurs", "Ralentisseur moteur : levier principal", ["Rétrogradation et régime moteur", "Serrage frein park", "Ouverture EGR seule", "Coupe ABS"], 0, "Choisir rapport adapté avant la pente.");
  Q("ralentisseurs", "Crans de ralentisseur ( 1-2-3 )", ["Puissance croissante selon modèle", "Vitesse maximale autorisée", "Niveau PTAC", "Pression park"], 0, "Plus le cran est haut, plus la décélération aide.");
  Q("ralentisseurs", "Ralentisseur ≠ frein de service", ["Vrai : rôles complémentaires", "Faux : identiques", "Le ralentisseur serre le park", "Le service remplace le moteur"], 0, "Ralentisseur = continu ; service = urgence et arrêt.");
  Q("ralentisseurs", "Température freins en descente : signe", ["Odeur, fade, allongement distance", "Voyant EGR", "PTAC diminue", "ABS clignote toujours"], 0, "Surchauffe = perte d'efficacité dangereuse.");
  Q("ralentisseurs", "Ralentisseur échappement désactivé", ["Moins d'aide en descente", "Plus de PTAC", "ESP coupé", "Frein park desserré"], 0, "Vérifier disponibilité avant longue pente.");
  Q("ralentisseurs", "Hydrodynamique : bruit caractéristique", ["Souvent bourdonnement en intervention", "Silence ABS", "Claquement embrayage seul", "Sifflement EGR"], 0, "Bruit normal du retarder en fonctionnement.");
  Q("ralentisseurs", "Électromagnétique : précaution", ["Peut chauffer : usage intermittent conseillé", "Usage continu sans limite", "Remplace ceinture", "Contrôle dimensions"], 0, "Comme freins, risque thermique si abus.");
  Q("ralentisseurs", "Neige : ralentisseur puissant", ["Risque de blocage essieu moteur", "Toujours recommandé maxi", "Coupe ASR volontairement", "Augmente PTRA"], 0, "Adapter puissance à l'adhérence.");
  Q("ralentisseurs", "Combinaison descente FIMO", ["Ralentisseur + frein service en relais", "Park + ABS", "EGR + ESP", "AFU seul"], 0, "Alterner pour refroidir tambours.");
  Q("ralentisseurs", "Ralentisseur moteur au ralenti bas", ["Peu efficace", "Maximum efficace", "Serre frein park", "Ouvre vanne EGR"], 0, "Il faut du régime pour freiner par moteur.");
  Q("ralentisseurs", "VEB inopérant : conduite", ["Anticiper freins service et vitesse basse", "Accélérer en descente", "Couper contact", "Relever semi"], 0, "Compenser par freinage service modéré.");
  Q("ralentisseurs", "Ralentisseurs et EBS", ["Peuvent être coordonnés selon véhicule", "Sans aucun lien possible", "L'EBS remplace les quatre", "Coupe hydrodynamique"], 0, "Électronique embarquée moderne.");
  Q("ralentisseurs", "Piège : frein service continu 8 km descente", ["Danger surchauffe : utiliser ralentisseur", "Recommandé FIMO", "Améliore ABS", "Réduit PTAC"], 0, "Classique piège examen descente.");
  Q("ralentisseurs", "Choix cran 3 en ville dense", ["Souvent excessif : adapter au contexte", "Toujours obligatoire", "Interdit", "Remplace freinage service"], 0, "Puissance à moduler selon trafic.");
  Q("ralentisseurs", "Retarder hydrodynamique usé", ["Efficacité réduite : contrôle atelier", "Plus de frein service", "PTAC 44 t auto", "ESP renforcé"], 0, "Entretien spécifique nécessaire.");
  Q("ralentisseurs", "Les 4 ralentisseurs : point commun", ["Aident à décélérer sans usure primaire freins service", "Remplacent ABS", "Mesurent surcharge", "Contrôlent EGR"], 0, "Complément au freinage pneumatique.");
  Q("ralentisseurs", "Signal ralentisseur au tableau de bord", ["Voyant ou indicateur selon type actif", "Voyant PTAC", "Voyant park desserré", "Voyant ceinture"], 0, "Savoir quel'aide est en fonction.");
  /* FREINAGE */
  Q("freinage", "Frein de service PL : principe", ["Air comprimé SERRE les freins", "Ressorts serrent en permanence", "Huile hydraulique seule", "EGR freine les roues"], 0, "Classique pneumatique : air = serrage service.");
  Q("freinage", "Frein de parc ( stationnement )", ["Ressorts SERREnt ; air DESSERRE", "Air serre ; ressorts desserrent", "Identique au frein service", "Coupe l'ABS"], 0, "Piège inverse : park = ressorts + air desserre.");
  Q("freinage", "Double circuit freinage PL", ["Séparation avant / arrière courante", "Un seul circuit sans secours", "Uniquement remorque", "Remplace ESP"], 0, "Si un circuit faiblit, l'autre peut aider.");
  Q("freinage", "Perte de pression air service", ["Freinage dégradé : arrêt sécurisé", "Accélération automatique", "PTAC réduit", "EGR ouverte"], 0, "Voyant rouge ou buzzer : s arrêter.");
  Q("freinage", "Frein de parc en roulant", ["Interdit sauf urgence extrême selon procédure", "Recommandé en descente", "Remplace ralentisseur", "Active AFU"], 0, "Risque de blocage et départ en toupie.");
  Q("freinage", "Seringue ou pompage pédale service", ["Signe possible de fuite ou usure", "Normal'ABS permanent", "EGR encrassée", "PTAC OK"], 0, "Faire contrôler le circuit pneumatique.");
  Q("freinage", "Réservoirs air : rôle", ["Stockage et stabilisation pression", "Mesure PTAC", "Alimentation EGR", "Contrôle ESP"], 0, "Réserve pour plusieurs freinages.");
  Q("freinage", "Compresseur air frein", ["Alimente les réservoirs", "Freine directement les roues sans air", "Remplace compresseur clim", "Mesure PTRA"], 0, "Entraîné par moteur.");
  Q("freinage", "Dessiccateur air", ["Retire humidité pour protéger circuit", "Augmente PTAC", "Contrôle ABS", "Régule EGR"], 0, "Eau dans circuit = corrosion et gel.");
  Q("freinage", "Purging circuit air", ["Évacuer eau/condensats régulièrement", "Inutile sur PL", "Remplace contrôle technique", "Coupe ASR"], 0, "Maintenance obligatoire bonne pratique.");
  Q("freinage", "Répartiteur charge ( selon véhicules )", ["Adapte pression AR à la charge", "Mesure longueur 16,50", "Contrôle vanne EGR", "Remplace ABS"], 0, "Remorque lourde = plus de pression AR.");
  Q("freinage", "Freinage remorque sans EBS", ["Synchronisation mécanique/pneumatique plus lente", "Impossible", "Identique toujours", "Coupe PTAC"], 0, "Délai air dans tuyaux longs.");
  Q("freinage", "Tambours surchauffés", ["Fade : distance allongée", "ABS coupé", "PTRA 26 t", "EGR fermée"], 0, "Signe d'usage excessif frein service.");
  Q("freinage", "Circuit avant faible en urgence", ["Moins de freinage avant possible", "Plus de freinage avant", "Park se serre", "ESP off"], 0, "Double circuit protège partiellement.");
  Q("freinage", "Stationnement pente : règle", ["Frein de parc + cales si nécessaire", "Service seul suffit toujours", "Couper contact suffit", "EGR maintient"], 0, "Park ressorts ; vérifier efficacité.");
  Q("freinage", "Voyant pression air basse", ["Ne pas repartir chargé : contrôler", "Ignorer", "Augmenter vitesse", "Couper ESP"], 0, "Sécurité freinage compromise.");
  Q("freinage", "Frein service + ABS", ["ABS module pression service", "ABS remplace air", "Sans lien", "ABS desserre park"], 0, "Même énergie pneumatique de base.");
  Q("freinage", "Attelage : tête de couverture ( gladhand )", ["Alimentation air frein remorque", "Prise EGR", "Mesure PTAC", "GPS remorque"], 0, "Deux conduites courantes rouge/jaune.");
  Q("freinage", "Déconnexion air remorque en route", ["Freinage remorque d'urgence possible", "Rien ne change", "PTAC augmente", "ESP renforce"], 0, "Freins remorque peuvent se serrer ( selon système ).");
  Q("freinage", "Contrôle freinage au départ", ["Pression OK, park desserré, essai court", "Uniquement en hiver", "Seulement 44 t", "Après 500 km"], 0, "Vérifications quotidiennes FIMO.");
  Q("freinage", "Freinage progressif en charge", ["Anticiper pour limiter à-coups attelage", "Freiner toujours à fond", "Utiliser park", "Couper moteur"], 0, "Confort et sécurité ensemble.");
  Q("freinage", "Différence clé service / park FIMO", ["Service : air serre ; Park : ressorts serrent, air desserre", "Identiques", "Park : air serre", "Service : ressorts"], 0, "Question classique piège examen.");
  Q("freinage", "Plaque de fondation frein park", ["Maintient ressorts de serrage", "Mesure CU", "Contrôle EGR", "Capteur ESP"], 0, "Mécanisme ressort + diaphragme.");
  /* ASR */
  Q("asr", "ASR signifie", ["Anti-Slip Regulation : antipatinage à l'accélération", "Automatic Stop Rear : frein arrière auto", "Air Storage Reserve : réserve air", "Adaptive Speed Road : régulateur"], 0, "L'ASR limite le patinage à l'accélération.");
  Q("asr", "L'ASR intervient quand", ["Les roues motrices patinent au démarrage ou en reprise", "Le véhicule freine en urgence", "Le PTAC est exact", "La remorque est vide"], 0, "Patinage = vitesse roue >> vitesse véhicule.");
  Q("asr", "Pour corriger, l'ASR peut", ["Réduire couple moteur et freiner roue motrice", "Augmenter injection maxi", "Serre frein de parc", "Ouvrir EGR"], 0, "Retrouver adhérence des roues motrices.");
  Q("asr", "ASR et ABS : complémentarité", ["ABS au freinage ; ASR à l'accélération", "Identiques", "ASR remplace ABS", "Sans lien"], 0, "Deux fonctions d'adhérence opposées.");
  Q("asr", "ASR sur sol boueux en côte", ["Aide à partir sans giration excessive", "Remplace chaînes obligatoires", "Augmente PTAC", "Coupe ESP"], 0, "Limite patinage qui creuse la voie.");
  Q("asr", "Voyant ASR clignotant", ["Intervention en cours", "Panne obligatoire", "Surcharge", "Frein park desserré"], 0, "Normal lors d'une correction.");
  Q("asr", "Désactiver ASR sur route glissante", ["Patinage plus difficile à contrôler", "Toujours recommandé", "Obligatoire FIMO", "Augmente PTRA"], 0, "Aide précieuse au démarrage chargé.");
  Q("asr", "ASR ≠ ESP", ["Vrai : ASR = patinage ; ESP = trajectoire", "Faux : identiques", "ESP patine", "ASR corrige virage"], 0, "Ne pas confondre au FIMO.");
  Q("asr", "ASR sur 2 essieux motrices", ["Peut agir sur un ou les deux essieux", "Uniquement essieu avant", "Uniquement remorque", "Jamais sur PL"], 0, "Selon architecture traction.");
  Q("asr", "Capteurs ASR", ["Vitesses de roue comme l'ABS", "Capteur EGR seul", "Jauge CU", "GPS"], 0, "Compare vitesse roues entre elles et véhicule.");
  Q("asr", "ASR et démarrage côte chargé", ["Réduit patinage et usure différentiel", "Remplace frein de parc", "Modifie PTAC carte", "Coupe AFU"], 0, "Démarrage plus progressif.");
  Q("asr", "Panne ASR", ["Patinage plus facile : modérer accélérateur", "Plus de moteur", "Freins coupés", "PTRA 19 t"], 0, "Conduite manuelle plus prudente.");
  Q("asr", "ASR intégré EBS", ["Fréquent sur PL récents", "Impossible", "Remplace embrayage", "Mesure 2,55 m"], 0, "Électronique freinage/moteur liée.");
  Q("asr", "Accélérateur à fond sur glace : ASR", ["Coupe ou réduit couple", "Augmente toujours couple", "Serre park", "Ouvre EGR max"], 0, "Empêche patinage incontrôlé.");
  Q("asr", "ASR en virage accéléré", ["Peut limiter couple si patinage", "Corrige trajectoire seul ( ESP )", "Remplace direction", "Modifie PTRA"], 0, "ASR gère adhérence longitudinale.");
  Q("asr", "Blocage différentiel + ASR", ["Usages différents : diff manuel terrain ; ASR auto", "Identiques", "ASR bloque diff", "Diff remplace ASR"], 0, "Ne pas confondre les aides.");
  Q("asr", "ASR et remorque lourde", ["Aide au démarrage sans flambée de patinage", "Inutile avec remorque", "Augmente surcharge essieu", "Coupe ABS"], 0, "Masse remorque = risque patinage accru.");
  Q("asr", "Message ASR off", ["Vérifier bouton ou défaut", "Gain vitesse", "PTAC +2 t", "Frein service off"], 0, "Système désactivé ou en anomalie.");
  Q("asr", "ASR ne remplace pas", ["Pneus adaptés et vitesse adaptée", "Calculateur moteur", "Capteurs roue", "Rien"], 0, "Aide électronique, pas pneus hiver magiques.");
  Q("asr", "Sur route sèche, ASR intervient", ["Rarement si adhérence bonne", "En permanence", "À chaque freinage", "Coupe moteur"], 0, "Pas de patinage = pas d'action.");
  Q("asr", "ASR et couple moteur élevé", ["Peut réduire couple pour garder grip", "Augmente couple maxi", "Modifie essieux loi", "Change largeur"], 0, "Priorité adhérence sur performance instantanée.");
  Q("asr", "En FIMO, ASR est associé à", ["Antipatinage accélération", "Antiblocage freinage", "Trajectoire ESP", "Recyclage EGR"], 0, "Retenir le A de Acceleration / Anti-patinage.");
  /* FRONT */
  Q("front", "Front Assist est", ["Un système d'aide à la anticollision", "Un régulateur de vitesse adaptatif", "Un frein de parc automatique", "Une vanne EGR"], 0, "Détection obstacle avant et alerte/freinage.");
  Q("front", "Front Assist utilise souvent", ["Radar ou caméra avant", "Capteur PTAC", "Jauge AdBlue seule", "Pression park"], 0, "Capteurs de distance avant.");
  Q("front", "En cas de risque de collision", ["Alerte puis freinage partiel ou total selon système", "Accélération pour dépasser", "Coupe ABS", "Ouvre EGR"], 0, "Chaîne alerte → intervention frein.");
  Q("front", "Front Assist ≠ ART", ["Vrai : anticollision vs régulateur adaptatif", "Identiques", "ART détecte obstacles", "Front Assist règle vitesse croisière"], 0, "Deux aides distinctes au FIMO.");
  Q("front", "Le conducteur avec Front Assist doit", ["Rester vigilant : aide limitée", "Dormir au volant", "Couper distance sécurité", "Ignorer obstacles"], 0, "L'aide ne remplace pas l'attention.");
  Q("front", "Front Assist limite de vitesse", ["Fonctionne surtout à basse/moyenne vitesse selon système", "Toujours à 130 km/h PL", "Uniquement à l'arrêt", "Seulement en marche arrière"], 0, "Performance varie selon équipement.");
  Q("front", "Obstacle détecté tardivement", ["Système peut ne pas éviter totalement", "Toujours arrêt garanti", "PTAC réduit", "ESP off"], 0, "Physique : vitesse et distance comptent.");
  Q("front", "Front Assist et véhicule devant freinant", ["Peut alerter ou freiner si écart insuffisant", "Remplace feux stop", "Augmente PTRA", "Coupe ASR"], 0, "Aide à réduire chocs arrière.");
  Q("front", "Désactiver Front Assist", ["Perd'une aide sécurité si disponible", "Obligatoire FIMO", "Améliore freinage", "Modifie PTAC"], 0, "Garder actif sauf cas particulier constructeur.");
  Q("front", "Front Assist ≠ freinage seul du conducteur", ["Complète, ne remplace pas", "Remplace totalement", "Identique park", "Coupe service"], 0, "Le pied reste indispensable.");
  Q("front", "Conditions limitant Front Assist", ["Mauvais temps, saleté capteur, virage serré", "Aucune limite", "Uniquement nuit", "Seulement 44 t"], 0, "Capteurs ont plages de fonctionnement.");
  Q("front", "Front Assist + ABS/EBS", ["Freinage d'urgence assisté coordonné", "Sans lien", "Coupe ABS", "Desserre park"], 0, "Systèmes intégrés sur véhicules récents.");
  Q("front", "Alerte sonore Front Assist", ["Invite à freiner ou à réagir", "Signe PTAC dépassé", "Active ralentisseur 3", "Ouvre EGR"], 0, "Premier niveau avant freinage auto.");
  Q("front", "Front Assist en embouteillage", ["Peut aider à éviter accrochages légers", "Conduit seul à 90 km/h", "Remplace ceinture", "Mesure CU"], 0, "Utile à faible vitesse dense.");
  Q("front", "Entretien Front Assist", ["Capteurs propres et calibrés", "Ignorer saleté pare-brise", "Gonflage 12 bar", "Réglage EGR"], 0, "Salissure = détection réduite.");
  Q("front", "Front Assist ne mesure pas", ["Le PTAC de l'ensemble", "Distance obstacle", "Vitesse relative", "Temps collision"], 0, "Pas un système pesage.");
  Q("front", "Piège FIMO : Front Assist", ["Anticollision avant", "Régulateur adaptatif ART", "Antipatinage ASR", "Recyclage EGR"], 0, "Associer Front = avant / collision.");
  Q("front", "Conducteur qui s'appuie sur l'aide", ["Retarde réaction : danger", "Recommandé", "Réduit conso", "Augmente PTRA"], 0, "Effet complacency interdit.");
  Q("front", "Front Assist intervention", ["Peut surprendre : freinage brusque possible", "Jamais perceptible", "Desserre service", "Coupe moteur seul"], 0, "Connaître son véhicule.");
  Q("front", "Voyant ou message Front Assist off", ["Vérifier défaut ou désactivation", "Normal permanent", "Surcharge OK", "Frein park seul"], 0, "Faire contrôler si anomalie.");
  Q("front", "Front Assist et remorque", ["Calibration et perf peuvent changer", "Toujours identique", "Interdit attelage", "Mesure 18,75 m"], 0, "Attelage modifie cinématique avant.");
  Q("front", "En FIMO, retenir Front Assist =", ["Aide anticollision", "Aide trajectoire ESP", "Frein park auto", "Contrôle surcharge"], 0, "Définition examen standard.");
  /* ART */
  Q("art", "ART signifie au FIMO", ["Adaptive Cruise Control : régulateur de vitesse adaptatif", "Automatic Retarder Tool : ralentisseur", "Anti-Roll Technology : antibasculement", "Air Reservoir Tank : réservoir"], 0, "ART = régulateur adaptatif ( ACC ).");
  Q("art", "L'ART maintient", ["Vitesse choisie en adaptant à la circulation", "PTAC automatique", "Pression park", "Température EGR"], 0, "Régulateur + gestion distance véhicule devant.");
  Q("art", "ART ≠ régulateur classique", ["L'ART ralentit si véhicule devant ralentit", "Identiques", "Le classique freine en urgence seul", "L'ART mesure PTAC"], 0, "Adaptation à l'écart de distance.");
  Q("art", "Réglage écart ART trop court", ["Yo-yo, stress, conso, risque accrochage", "Toujours le plus sûr", "Obligatoire FIMO", "Coupe Front Assist"], 0, "Distance = marge de sécurité.");
  Q("art", "ART en descente", ["Peut demander freinage ou ralentisseur selon système", "Désactive freins", "Augmente PTAC", "Coupe ABS"], 0, "Maintien vitesse avec moyens disponibles.");
  Q("art", "Désactiver ART en ville dense", ["Parfois préférable pour contrôle manuel", "Interdit", "Obligatoire autoroute", "Modifie PTRA"], 0, "Trafic complexe = pilotage manuel.");
  Q("art", "ART ≠ Front Assist", ["ART = vitesse ; Front Assist = collision", "Identiques", "ART détecte obstacles latéraux", "Front Assist règle vitesse"], 0, "Ne pas inverser au examen.");
  Q("art", "Capteurs ART", ["Radar/lidar/caméra avant selon véhicule", "Capteur CU", "Jauge AdBlue", "Pression service"], 0, "Mesure distance et vitesse relative.");
  Q("art", "ART et véhicule devant accélère", ["Peut réaccélérer jusqu à consigne", "Freine à fond", "Coupe moteur", "Serre park"], 0, "Reprend vitesse si voie libre.");
  Q("art", "Limite ART : coupure radar", ["Pluie forte, saleté, obstacle hors champ", "Aucune", "Uniquement nuit", "Seulement 44 t"], 0, "Conditions dégradées = vigilance.");
  Q("art", "ART ne remplace pas", ["Regard et anticipation du conducteur", "Freins service", "Permis C", "Toutes les réponses"], 3, "Aide confort/sécurité, pas autopilot.");
  Q("art", "Réglage vitesse ART au-dessus limite", ["Interdit : respecter réglementation", "Autorisé FIMO", "Recommandé", "Augmente PTRA"], 0, "Le conducteur reste responsable.");
  Q("art", "ART + frein moteur", ["Peut combiner décélération douce", "Interdit", "Coupe EBS", "Ouvre EGR"], 0, "Stratégie économie selon calculateur.");
  Q("art", "Message ART indisponible", ["Repasser en régulation manuelle", "Arrêt obligatoire", "PTAC réduit", "ESP off"], 0, "Continuer sans aide adaptative.");
  Q("art", "ART écart long autoroute", ["Confort et conso, marge temps réaction", "Toujours dangereux", "Interdit PL", "Remplace ABS"], 0, "Bon compromis PL lourd.");
  Q("art", "Conducteur doit garder mains volant", ["Oui, ART n est pas conduite autonome", "Non, mains libres", "Seulement en ville", "Uniquement de nuit"], 0, "Systèmes niveau 1-2 maxi.");
  Q("art", "ART en chaussée mouillée", ["Allonger écart et réduire vitesse consigne", "Identique sec", "Couper freins", "Relever essieu"], 0, "Distance freinage allongée.");
  Q("art", "Piège : ART = régulateur", ["Adaptatif avec gestion distance", "Frein urgence AFU", "Antipatinage ASR", "Vanne EGR"], 0, "Mot clé : adaptatif.");
  Q("art", "ART désactivé : conséquence", ["Gestion vitesse manuelle", "Freins coupés", "Surcharge", "EGR bloquée"], 0, "Simple régulateur ou rien selon modèle.");
  Q("art", "Entretien ART", ["Capteurs avant propres", "Vidange pont", "Gonflage 15 bar", "Réglage park"], 0, "Comme Front Assist, capteurs sensibles.");
  Q("art", "ART et embouteillage", ["Stop-and-go parfois géré selon système", "Toujours 90 km/h", "Interdit", "Mesure dimensions"], 0, "Limites selon constructeur.");
  Q("art", "En FIMO, ART se distingue de Front Assist par", ["Régulation vitesse vs urgence collision", "Couleur voyant", "Pression air", "Nombre essieux"], 0, "Deux rôles complémentaires mais distincts.");
  /* CONDUITE */
  Q("conduite", "Conduite rationnelle PL : objectif", ["Sécurité, conso, usure, respect réglement", "Vitesse maxi permanente", "PTAC maxi systématique", "Couper ABS"], 0, "Équilibre économie et sécurité.");
  Q("conduite", "Anticipation en PL", ["Réduit freinages et accélérations inutiles", "Inutile avec ESP", "Remplace ralentisseur", "Modifie PTRA"], 0, "Voir loin = économie carburant.");
  Q("conduite", "Régime moteur optimal conso", ["Zone verte constructeur, pas sur-régime", "Toujours régime maxi", "500 tr/min en côte", "Ralenti élevé permanent"], 0, "Courbe consommation ≠ couple maxi.");
  Q("conduite", "Éco-conduite en côte", ["Anticiper sommet, éviter accélération tardive", "Accélérer à fond en haut", "Couper moteur", "Frein park"], 0, "Conserver inertie sans forcer.");
  Q("conduite", "Distance sécurité PL chargé", ["Supérieure à voiture légère", "Identique voiture", "Inutile avec ABS", "1 seconde suffit"], 0, "Masse et distance freinage augmentées.");
  Q("conduite", "Ralenti prolongé inutile", ["Consommation et pollution", "Recommandé hiver seul", "Améliore ABS", "Réduit PTAC"], 0, "Couper si arrêt > quelques secondes ( selon contexte ).");
  Q("conduite", "Pression pneus sous-gonflés", ["Conso + usure + surchauffe", "Meilleure adhérence toujours", "Augmente PTAC légal", "Active ESP"], 0, "Contrôle régulier indispensable.");
  Q("conduite", "Aérodynamisme : toit deflector", ["Réduit traînée à vitesse", "Augmente PTAC", "Coupe ASR", "Remplace arrimage"], 0, "Utile autoroute.");
  Q("conduite", "Changement vitesse précoce ( short shift )", ["Peut économiser si couple suffisant", "Toujours calage", "Interdit PL", "Coupe freinage"], 0, "Ne pas lugger le moteur.");
  Q("conduite", "Frein moteur préventif", ["Limite usage frein service", "Remplace ABS", "Augmente surcharge", "Ouvre EGR"], 0, "Complément éco et sécurité descente.");
  Q("conduite", "Charge mal répartie", ["Usure pneus, conso, risque surcharge essieu", "Sans effet", "Améliore ESP", "Réduit PTRA"], 0, "Centrage et répartition masses.");
  Q("conduite", "Conduite agressive", ["Conso, usure freins, risque accident", "Recommandée FIMO", "Active ART maxi", "Réduit PTAC"], 0, "Style pro = progressif.");
  Q("conduite", "Planification trajet PL", ["Évite km, pentes, embouteillages", "Inutile GPS", "Modifie essieux", "Coupe EBS"], 0, "Organisation = économie.");
  Q("conduite", "Vitesse adaptée météo", ["Obligatoire même avec ABS/ESP", "Facultatif", "Uniquement nuit", "Seulement 44 t"], 0, "Aides ne créent pas adhérence.");
  Q("conduite", "Couper moteur en descente", ["Dangereux : plus de frein moteur ni assistance", "Économique FIMO", "Active ralentisseur", "Réduit PTRA"], 0, "Perte assistance direction si contact coupé.");
  Q("conduite", "Utilisation clim/chauffage excessif", ["Impact conso", "Sans effet", "Améliore ABS", "Modifie PTAC"], 0, "Auxiliaires consomment.");
  Q("conduite", "Reprise après arrêt longue descente", ["Vérifier freins avant repartir", "Accélérer direct", "Couper ESP", "Relever semi"], 0, "Freins peuvent être chauds/fadés.");
  Q("conduite", "Conduite de nuit PL", ["Fatigue accrue : pauses obligatoires", "Identique jour", "Sans limite", "Coupe AFU"], 0, "Réglementation temps conduite/repose.");
  Q("conduite", "Surconsommation freins", ["Signe mauvaise anticipation", "Normal FIMO", "Defaut EGR seul", "PTAC bas"], 0, "Trop de frein service = mauvaise gestion.");
  Q("conduite", "Éco-conduite ≠ rouler lentement partout", ["Régime et anticipation optimisés", "30 km/h autoroute", "Couper ralentisseur", "Surcharge volontaire"], 0, "Efficience, pas lenteur systématique.");
  Q("conduite", "Arrimage marchandise", ["Sécurité + stabilité + conso indirecte", "Facultatif vrac", "Remplace ESP", "Modifie carte grise"], 0, "Charge mobile = accident.");
  Q("conduite", "Lecture tableau de bord", ["Repérer défauts tôt", "Inutile avec ART", "Remplace contrôle", "Coupe ASR"], 0, "Voyants moteur, air, ABS, etc.");
  Q("conduite", "Conduite rationnelle en ville", ["Flux fluide, éviter accélérations répétées", "Coups gaz maxi", "Frein park fréquent", "EGR coupée"], 0, "Urbain = conso et usure élevées si brutal.");
  Q("conduite", "Objectif FIMO conduite", ["Professionnelle, économique, sécurisée", "Sportive", "PTAC maxi toujours", "Sans ralentisseur"], 0, "Triptyque sécurité-éco-réglement.");
  /* COUPLE */
  Q("couple", "Couple moteur s exprime en", ["Newton-mètres ( N.m )", "Kilowatts seulement", "Bars de pression", "Tonnes PTAC"], 0, "Couple = force de rotation au vilebrequin.");
  Q("couple", "Puissance moteur dépend de", ["Couple et régime ( P ≈ C × n )", "PTAC uniquement", "Largeur remorque", "Pression park"], 0, "Plus de régime avec couple suffisant = plus de puissance.");
  Q("couple", "Zone couple maxi constructeur", ["Régime où accélérer chargé est efficace", "500 tr/min", "Vitesse maxi véhicule", "Pression ABS"], 0, "Tenir le moteur dans la plage utile.");
  Q("couple", "Sous-régime lourd ( lug )", ["Consommation et usure accrues", "Économique", "Active ESP", "Réduit PTRA"], 0, "Moteur forcé à bas régime haute charge.");
  Q("couple", "Sur-régime prolongé", ["Conso et usure", "Toujours optimal", "Coupe ABS", "Augmente PTAC"], 0, "Au-delà zone verte = gaspillage.");
  Q("couple", "Couple et démarrage côte", ["Rapport bas + couple dispo", "Rapport haut", "Frein park", "EGR ouverte"], 0, "Démultiplication favorise couple roues.");
  Q("couple", "Turbo sur PL diesel", ["Augmente couple à régime utile", "Remplace embrayage", "Mesure PTAC", "Coupe ASR"], 0, "Air comprimé admission = plus de couple.");
  Q("couple", "Consommation et couple", ["Bon couple à bon régime limite sur-régime", "Couple maxi = conso mini toujours", "Sans lien", "Couple coupe ESP"], 0, "Pilotage régime = éco-conduite.");
  Q("couple", "Puissance KW carte grise", ["Indique puissance fiscale/ maxi moteur", "Indique PTAC", "Indique PTRA", "Indique CU"], 0, "Ne pas confondre avec masses.");
  Q("couple", "Couple roues vs couple moteur", ["Couple roues plus élevé ( démultiplication )", "Identiques", "Couple roues plus faible", "Sans transmission"], 0, "Boîte et pont multiplient le couple.");
  Q("couple", "Calage moteur en côte", ["Rétrograder avant perte vitesse", "Maintenir rapport haut", "Couper contact", "Frein park"], 0, "Conserver régime dans zone couple.");
  Q("couple", "Couple et remorque lourde", ["Demande rapport adapté et anticipation", "Sans effet", "Réduit PTAC tracteur", "Coupe EBS"], 0, "Masse totale influence accélération.");
  Q("couple", "Limite couple différentiel", ["Peut patiner si adhérence faible", "Infini toujours", "Mesure 2,55 m", "Active AFU"], 0, "Couple transmis limité par grip.");
  Q("couple", "Ralentisseur et régime", ["Frein moteur fort si régime monté", "Régime bas = maxi frein moteur", "Sans lien", "Coupe turbo"], 0, "Compression depend du régime.");
  Q("couple", "Consommation autoroute PL", ["Stabiliser vitesse, rapport adapté", "Accélérer freiner souvent", "Couper ABS", "PTAC maxi"], 0, "Régularité = économie.");
  Q("couple", "Couple bridé mode dégradé", ["Peut suivre défaut EGR/SCR", "Augmente PTAC", "Active ESP max", "Coupe freins"], 0, "Protection moteur antipollution.");
  Q("couple", "Pont court vs long", ["Court : couple roues, moins vitesse", "Long : plus couple roues", "Identiques", "Mesure PTRA"], 0, "Choix métier chantier vs route.");
  Q("couple", "Couple et ASR", ["ASR limite couple si patinage", "ASR augmente couple maxi", "Sans lien", "ASR mesure PTAC"], 0, "Gestion électronique adhérence.");
  Q("couple", "Full throttle en bas régime chargé", ["Mauvais pour conso et mécanique", "Recommandé FIMO", "Active ART", "Réduit surcharge"], 0, "Adapter rapport avant d'appuyer.");
  Q("couple", "Puissance utile en côte", ["Couple à régime moyen-élevé", "Puissance à l'arrêt max", "EGR seule", "Frein service"], 0, "Besoin couple plus que pic puissance.");
  Q("couple", "Lecture tachymètre pro", ["Régime cible selon charge", "Toujours zone rouge", "Ignorer", "Remplace contrôle air"], 0, "Outil éco-conduite.");
  Q("couple", "Couple et surconsommation", ["Mauvais rapport = surconsommation", "Sans effet", "Améliore ABS", "Modifie essieux"], 0, "Même vitesse, mauvais régime = plus de gasoil.");
  /* SURCHARGE */
  Q("surcharge", "Surcharge PTAC signifie", ["Masse réelle supérieure au PTAC autorisé", "Remorque absente", "Pneu usé", "EGR encrassée"], 0, "Dépassement masse véhicule seul.");
  Q("surcharge", "Surcharge essieu", ["Charge sur un essieu dépasse limite même si total OK", "PTAC dépassé seulement", "PTRA toujours OK", "Sans sanction"], 0, "Piège classique pont-bascule.");
  Q("surcharge", "Conséquence surcharge", ["Freinage allongé, pneus, chaussée, sanctions", "Meilleure adhérence", "ABS renforcé", "PTRA augmenté"], 0, "Risques mécaniques et juridiques.");
  Q("surcharge", "Pont-bascule : 19,8 t pour PTAC 19 t", ["Surcharge : ne pas partir", "Tolérance OK", "ABS compense", "EGR calcule"], 0, "Esprit FIMO : respect strict masses.");
  Q("surcharge", "CU et surcharge", ["Charger au-delà CU = surcharge tracteur", "CU illimitée", "CU = PTRA", "CU remplace PTAC"], 0, "CU = MMA - PV.");
  Q("surcharge", "Ensemble PTRA dépassé", ["Surcharge ensemble même si tracteur seul OK", "Sans importance", "Autorisé 5 %", "ESP compense"], 0, "PTRA limite l'attelage chargé.");
  Q("surcharge", "Produit dense demi-citerne", ["Peut être plein en masse avec faible volume visible", "Impossible surcharger", "Volume = masse toujours", "EGR mesure"], 0, "Se fier au pesage, pas au niveau seul.");
  Q("surcharge", "Sanction surcharge France ( ordre idée )", ["Amende, immobilisation possible, FCO...", "Aucune", "Uniquement avertissement", "Réduction PTAC carte"], 0, "Gravité selon écart et récidive.");
  Q("surcharge", "Surcharge avant essieu", ["Direction et freinage avant dégradés", "Sans effet", "Améliore ASR", "Réduit longueur"], 0, "Essieu directeur surchargé = dangereux.");
  Q("surcharge", "Relevé essieu pour surcharger", ["Interdit : triche contrôle", "Autorisé FIMO", "Recommandé", "Augmente PTRA"], 0, "Relevé pour manœuvre ou pneus vides.");
  Q("surcharge", "Contrôle avant départ", ["Pesée ou estimation sérieuse selon flux", "Jamais", "Seulement 44 t", "Après 500 km"], 0, "Responsabilité conducteur/exploitant.");
  Q("surcharge", "Surcharge et freinage", ["Distance d'arrêt augmentée", "ABS supprime effet", "AFU annule", "Park suffit"], 0, "Énergie cinétique plus élevée.");
  Q("surcharge", "Palettes mal réparties avant", ["Risque surcharge essieu directeur", "Sans effet", "Modifie largeur", "Active ESP max"], 0, "Répartition aussi importante que total.");
  Q("surcharge", "Surcharge répétée", ["Usure pneus, suspension, image entreprise", "Sans conséquence", "Bonus conso", "PTAC carte augmente"], 0, "Coût caché important.");
  Q("surcharge", "Documentation transport", ["Doit être cohérente avec masses chargées", "Facultative", "Remplace permis", "Mesure ABS"], 0, "Lettre voiture, bordereaux...");
  Q("surcharge", "Surcharge légère habituelle", ["Reste illégale et dangereuse", "Tolérée systématiquement", "Recommandée", "Active ART"], 0, "Pas de « un peu c'est rien » au FIMO.");
  Q("surcharge", "Vrac mal nivelé", ["Surcharge essieu localisée possible", "Impossible", "Réduit PTRA", "Coupe EGR"], 0, "Centre de gravité et répartition variables.");
  Q("surcharge", "Surcharge hiver boue", ["Enlisement + casse plus probables", "Meilleure motricité", "ASR inutile", "PTAC +2 t"], 0, "Masse excessive sur sol faible.");
  Q("surcharge", "Responsable surcharge", ["Conducteur et exploitant selon cas", "Uniquement client", "Uniquement garagiste", "Personne"], 0, "Chaîne responsabilité transport.");
  Q("surcharge", "Corriger surcharge avant route", ["Décharger ou répartir", "Accélérer vite", "Couper ESP", "Relever essieu"], 0, "Retour quai si nécessaire.");
  Q("surcharge", "Surcharge et pneus", ["Surchauffe, éclatement, usure", "Meilleure tenue", "Sans effet", "Gonflage inutile"], 0, "Pneus dimensionnés pour charge maxi.");
  Q("surcharge", "Piège FIMO surcharge", ["Total OK mais essieu KO possible", "Seul PTAC compte", "PTRA sans limite", "ESP corrige masse"], 0, "Trois contrôles : essieu, PTAC, PTRA.");
  /* PTAC */
  Q("ptac", "PTAC d'un porteur isolé correspond à", ["MMA du véhicule seul", "MMA tracteur + semi", "PTRA ensemble", "CU remorque"], 0, "Isolé : PTAC = masse maxi administratively du porteur.");
  Q("ptac", "PTAC tracteur seul ( isolé )", ["MMA inscrite tracteur seul", "Somme PTAC tracteur + semi", "PTRA", "PV remorque"], 0, "Ne pas confondre avec ensemble.");
  Q("ptac", "PTAC semi-remorque", ["MMA de la semi seule", "MMA tracteur", "PTRA", "CU tracteur"], 0, "Carte grise semi = masse semi seule.");
  Q("ptac", "PTAC 19 t typique", ["Porteur 2 essieux courant", "Train 5 essieux", "Semi 3 essieux seule", "Tracteur 3 essieux seul"], 0, "2 essieux porteur = 19 t fréquent.");
  Q("ptac", "PTAC 26 t porteur", ["3 essieux porteur", "2 essieux", "4 essieux moteur", "Semi 2 essieux"], 0, "3 essieux = 26 t porteur/remorque.");
  Q("ptac", "PTAC 32 t", ["4 essieux moteur porteur", "2 essieux porteur", "Semi seule 2 essieux", "Tracteur 2 essieux"], 0, "4 essieux moteur = 32 t.");
  Q("ptac", "PV ( poids à vide ) sert à", ["Calculer CU = MMA - PV", "Remplacer PTAC", "Définir PTRA", "Mesurer longueur"], 0, "Charge utile disponible.");
  Q("ptac", "CU = 12 t, charge 11,5 t", ["Dans limite CU", "Surcharge", "PTRA dépassé", "Sans lien PTAC"], 0, "Reste sous charge utile.");
  Q("ptac", "PTAC ≠ PTRA", ["PTAC = seul ; PTRA = ensemble", "Identiques", "PTAC = remorque seule toujours", "PTRA = porteur seul"], 0, "Distinction fondamentale FIMO.");
  Q("ptac", "Carte grise porteur : MMA 19 t", ["PTAC isolé = 19 t", "PTRA 19 t", "Ensemble 38 t auto", "Semi 19 t"], 0, "MMA carte = PTAC en isolé.");
  Q("ptac", "PTAC tracteur 7 t + semi PTAC 33 t", ["Deux PTAC distincts, pas additionnés pour isolé", "PTAC ensemble 40 t", "Tracteur PTAC 40 t", "Semi sans PTAC"], 0, "Chaque véhicule a son PTAC propre.");
  Q("ptac", "PTAC et contrôle routier", ["Basé sur carte grise du véhicule", "Estimation visuelle seule", "Sans contrôle", "EGR mesure"], 0, "Document officiel prime.");
  Q("ptac", "PTAC semi 2 essieux courant", ["Jusqu à 36 t selon config ( 37+ pour 44 t )", "19 t", "12 t", "32 t porteur"], 0, "Semi lourde 2 essieux = PTAC élevé.");
  Q("ptac", "PTAC dépassé tracteur seul", ["Surcharge même sans remorque", "OK si PTRA bon", "OK si ESP on", "Sans sanction"], 0, "Limite véhicule seul.");
  Q("ptac", "PTAC porteur 12 t longueur maxi", ["12 m ( porteur isolé )", "16,50 m", "18,75 m", "2,55 m"], 0, "Ne pas mélanger masse et longueur.");
  Q("ptac", "PTAC remorque 3 essieux et plus", ["26 t ( règle courante FIMO )", "19 t", "32 t", "44 t"], 0, "Remorque lourde multi-essieux.");
  Q("ptac", "MMA et PTAC en FIMO isolé", ["Confondus : même valeur", "MMA > PTAC toujours", "PTAC > MMA", "Sans lien"], 0, "Isolé MMA = PTAC.");
  Q("ptac", "PTAC tracteur route 2 essieux", ["Souvent 19 t ( selon carte )", "32 t systématique", "26 t obligatoire", "44 t"], 0, "Lire carte grise tracteur.");
  Q("ptac", "Charge utile tracteur 19 t, PV 7,5 t", ["CU = 11,5 t", "CU = 19 t", "CU = 7,5 t", "PTAC = 7,5 t"], 0, "19 - 7,5 = 11,5 t charge possible.");
  Q("ptac", "PTAC et essieux", ["PTAC maxi lié au nombre essieux", "Indépendant essieux", "Un essieu = 32 t", "Sans limite"], 0, "Loi des essieux fixe plafonds.");
  Q("ptac", "Piège : PTAC ensemble articulé", ["Chaque véhicule garde son PTAC propre", "PTAC = somme deux PTAC", "PTAC = PTRA", "PTAC tracteur seul suffit"], 0, "Ensemble limité par PTRA et loi essieux.");
  Q("ptac", "PTAC semi pour dossier 44 t", ["Semi 2 ess : PTAC ≥ 37 t ; 3 ess : ≥ 38 t", "19 t suffit", "26 t suffit", "Sans condition"], 0, "Conditions spécifiques 44 t.");
  /* PTRA */
  Q("ptra", "PTRA définit", ["Masse maxi de l'ensemble routier", "Masse tracteur seul", "PV remorque", "CU semi"], 0, "Ensemble = tracteur + remorque chargés.");
  Q("ptra", "3e critère MMA d'un articulé (addition)", ["PV tracteur + PTAC semi", "PTAC tracteur + PTAC semi", "PTAC tracteur seul", "CU tracteur + CU semi"], 0, "Piège : on n'ajoute pas les deux PTAC.");
  Q("ptra", "L'ensemble est aussi limité par", ["La loi des essieux et l'addition", "La couleur de cabine", "L'EGR", "L'ABS seul"], 0, "On garde le plus petit : PTRA, essieux, addition.");
  Q("ptra", "PTRA 38 t ensemble 4 essieux", ["Règle courante FIMO", "19 t", "26 t", "12 t"], 0, "4 essieux ensemble = 38 t fréquent.");
  Q("ptra", "PTRA 40 t ensemble 5 essieux et plus", ["Règle courante", "32 t", "19 t", "Sans limite"], 0, "5+ essieux = 40 t possible.");
  Q("ptra", "PTRA 44 t conditions incluent", ["≥5 essieux, PTRA 44 carte, pneus, semi PTAC mini", "2 essieux suffisent", "Sans condition semi", "EGR neuve"], 0, "Dossier lourd exceptionnel.");
  Q("ptra", "Tracteur PV 8 t + semi PTAC 32 t. Addition articulé =", ["40 t", "32 t", "8 t", "24 t"], 0, "PV tracteur + PTAC semi = 8 + 32 = 40 t.");
  Q("ptra", "PTRA atteint mais essieu surchargé", ["Interdit : essieu prime aussi", "OK total", "ESP compense", "AFU valide"], 0, "Double contrôle masse.");
  Q("ptra", "PTRA train routier", ["Addition porteur + remorque selon règles", "PTAC tracteur seul", "Semi seule", "Sans limite"], 0, "Train = porteur + remorque.");
  Q("ptra", "PTRA 40 t, pont 40,5 t", ["Surcharge ensemble", "Tolérance FIMO", "OK ABS", "Réduit PTAC"], 0, "Dépassement même léger = surcharge.");
  Q("ptra", "PTRA carte grise tracteur 40 t", ["Plafond ensemble si attelage compatible", "Limite tracteur seul", "Limite semi seule", "CU tracteur"], 0, "Inscrit sur carte tracteur routier.");
  Q("ptra", "Ensemble 3 essieux total", ["Souvent plafond 26 t ( selon config )", "40 t", "44 t auto", "38 t"], 0, "Peu d'essieux = masse modérée.");
  Q("ptra", "PTRA vs PTAC tracteur", ["PTRA ≥ charge ensemble ; PTAC = tracteur seul", "Identiques", "PTRA = PV", "PTAC = ensemble"], 0, "Ne pas inverser.");
  Q("ptra", "Piège FIMO PTRA articulé", ["PV tracteur + PTAC semi", "PTAC + PTAC", "PTRA = PTAC semi", "PTRA = CU"], 0, "Formule examen incontournable.");
  Q("ptra", "Dossier 44 t : semi 2 essieux PTAC mini", ["37 t", "26 t", "19 t", "32 t"], 0, "Condition 44 t semi bicorne.");
  Q("ptra", "Dossier 44 t : semi 3 essieux PTAC mini", ["38 t", "37 t", "26 t", "19 t"], 0, "Tridem semi pour 44 t.");
  Q("ptra", "PTRA et longueur 16,50 m", ["Articulé maxi longueur, indépendant mais cohérent dossier", "PTRA 12 t", "Sans lien", "PTRA 18,75 m"], 0, "Masses et dimensions dossiers liés.");
  Q("ptra", "Ensemble 5 essieux PTRA 40 t", ["Conforme règle 5+ essieux", "Impossible", "Nécessite 44 t", "Limite 26 t"], 0, "Correspondance essieux/PTRA.");
  Q("ptra", "PTRA 42 t, loi des essieux 40 t. MMA =", ["40 t", "42 t", "44 t", "26 t"], 0, "On garde le plus petit des critères.");
  Q("ptra", "Remorque non compatible PTRA tracteur", ["Ne pas former ensemble au-delà", "Toujours 44 t", "ESP gère", "Sans contrôle"], 0, "Compatibilité attelage et masses.");
  Q("ptra", "PTRA dépassé : conséquence", ["Surcharge ensemble, freinage/allongement", "Rien", "ABS annule", "PTAC augmente"], 0, "Sanctions et risques accrus.");
  Q("ptra", "Train routier PTRA", ["Addition réglementaire selon essieux", "PTAC semi seul", "PV seul", "EGR"], 0, "Calcul spécifique train 18,75 m maxi.");
  /* DIMENSIONS */
  Q("dimensions", "Longueur maxi porteur isolé France", ["12 m", "16,50 m", "18,75 m", "2,55 m"], 0, "Triade FIMO : 12 / 16,50 / 18,75.");
  Q("dimensions", "Longueur maxi articulé ( tracteur + semi )", ["16,50 m", "12 m", "18,75 m", "4 m"], 0, "Semi classique autoroutière.");
  Q("dimensions", "Longueur maxi train routier", ["18,75 m", "16,50 m", "12 m", "2,60 m"], 0, "Porteur + remorque.");
  Q("dimensions", "Largeur maxi courante PL France", ["2,55 m", "2,60 m", "3 m", "4 m"], 0, "2,55 m standard.");
  Q("dimensions", "Largeur 2,60 m autorisée pour", ["Ensemble frigorifique ( dérogation courante )", "Tous PL sans condition", "Semi seule toujours", "Porteur béton"], 0, "Frigo = 2,60 m enseigné FIMO.");
  Q("dimensions", "Hauteur France enseignement FIMO", ["Souvent pas de limite stricte ; 4 m repère pratique", "2,55 m", "12 m", "19 t"], 0, "4 m = gabarit pratique ponts/portiques.");
  Q("dimensions", "Dépassement avant 12 m porteur", ["Interdit sans autorisation", "Toléré 50 cm", "OK ESP", "Réduit PTAC"], 0, "Longueur réglementée.");
  Q("dimensions", "16,50 m concerne", ["Articulé", "Porteur seul", "Train routier", "Semi seule sans tracteur"], 0, "Ne pas appliquer au train.");
  Q("dimensions", "18,75 m concerne", ["Train routier porteur + remorque", "Articulé", "Porteur", "Bus"], 0, "Plus long cas courant marchandises.");
  Q("dimensions", "Largeur 2,55 m : piège", ["Ne pas confondre avec longueur 12 m", "Égale hauteur 4 m", "Égale PTAC 19 t", "Égale PTRA 40 t"], 0, "Dimensions L/l/H distinctes.");
  Q("dimensions", "Gabarit 4 m hauteur : risque", ["Ponts, portiques, branches", "PTAC", "ABS", "EGR"], 0, "Anticiper itinéraire.");
  Q("dimensions", "Dépassement latéral marchandise", ["Interdit au-delà largeur sans dérogation", "Libre", "OK 20 cm", "ESP gère"], 0, "Largeur véhicule + charge.");
  Q("dimensions", "Longueur et PTAC", ["Indépendants mais même dossier véhicule", "PTAC = longueur", "12 m = 12 t", "Identiques"], 0, "Ne pas mélanger unités.");
  Q("dimensions", "Semi 13,60 m type", ["Compatible articulé 16,50 m total", "Train 18,75 m", "Porteur 12 m", "Largeur 4 m"], 0, "Longueur semi dans total articulé.");
  Q("dimensions", "Indicateur dépassement arrière", ["Obligatoire si charge dépasse", "Facultatif toujours", "Remplace feux", "Mesure PTAC"], 0, "Signalisation protrusion.");
  Q("dimensions", "Dimensions et 44 t", ["Dossier lourd ≠ dépassement gabarit libre", "44 t = plus large", "44 t = plus long libre", "Sans lien"], 0, "44 t = masse, pas gabarit extra.");
  Q("dimensions", "Porteur 12 m + remorque : type ensemble", ["Train routier si attelage porteur-remorque", "Articulé", "Porteur isolé", "Semi"], 0, "Type attelage définit règles.");
  Q("dimensions", "Largeur rétroviseurs", ["Peut dépasser largeur corps sous conditions", "Interdit toujours", "Compte dans 2,55 m corps", "Sans règle"], 0, "Rétros en plus du corps.");
  Q("dimensions", "Hauteur centre gravité", ["Stabilité : pas une limite 4 m stricte partout", "Égale PTAC", "Mesure PTRA", "Coupe ABS"], 0, "4 m = gabarit route, pas CG.");
  Q("dimensions", "Piège dimensions FIMO", ["12 / 16,50 / 18,75 et 2,55 ( 2,60 frigo )", "19 / 26 / 32 t", "ABS ESP AFU", "PV + PTAC"], 0, "Apprendre triade longueurs + largeurs.");
  Q("dimensions", "Autorisation transport exceptionnel", ["Hors gabarit standard", "Remplace permis C", "Augmente PTAC auto", "Coupe ESP"], 0, "Convoi / indivisible selon cas.");
  Q("dimensions", "Contrôle gabarit route", ["Respect longueur/largeur/hauteur pratique", "Uniquement PTAC", "Sans contrôle", "EGR mesure"], 0, "Gabarit = circulation légale.");
  /* ESSIEUX */
  Q("essieux", "2 essieux porteur : PTAC maxi courant", ["19 t", "26 t", "32 t", "38 t"], 0, "Règle de base FIMO.");
  Q("essieux", "3 essieux porteur ou remorque : PTAC maxi", ["26 t", "19 t", "32 t", "40 t"], 0, "3 essieux = 26 t.");
  Q("essieux", "4 essieux moteur porteur : PTAC maxi", ["32 t", "26 t", "19 t", "44 t"], 0, "4 essieux moteur = 32 t.");
  Q("essieux", "Remorque 3 essieux et plus : PTAC maxi", ["26 t", "19 t", "32 t", "12 t"], 0, "Remorque lourde multi-essieux.");
  Q("essieux", "Ensemble 4 essieux : masse maxi courante", ["38 t", "40 t", "26 t", "19 t"], 0, "4 essieux total'ensemble.");
  Q("essieux", "Ensemble 5 essieux et plus : masse maxi", ["40 t ( 44 t si conditions )", "26 t", "32 t", "19 t"], 0, "5+ essieux = 40 t ou 44 t dossier.");
  Q("essieux", "44 t : nombre essieux minimum", ["5 essieux", "2 essieux", "3 essieux", "4 essieux"], 0, "Condition dossier 44 t.");
  Q("essieux", "44 t : charges essieu plus sévères", ["Oui, essieu chargé souvent 12 t, tridem 27 t", "Non, identiques 19 t", "Sans limite essieu", "15 t par essieu"], 0, "44 t ≠ essieux libres.");
  Q("essieux", "Essieu surchargé, total OK", ["Interdit", "Autorisé FIMO", "OK si ABS", "OK si 44 t"], 0, "Contrôle pont-bascule par essieu.");
  Q("essieux", "Relevé essieu pour répartir masse", ["Manœuvre technique, pas triche pesée", "Pour dépasser 44 t", "Remplace contrôle", "Coupe ESP"], 0, "Usage ponctuel autorisé contexte.");
  Q("essieux", "Tridem : charge maxi en 44 t ( enseigné )", ["27 t sur groupe", "19 t", "32 t", "40 t seul"], 0, "Groupe 3 essieux arrière limité.");
  Q("essieux", "Essieu directeur surchargé", ["Direction et freinage dégradés", "Sans effet", "Améliore ASR", "Augmente PTRA"], 0, "Essieu avant critique.");
  Q("essieux", "Loi essieux vs PTRA", ["Prendre le plus restrictif", "PTRA seul compte", "Essieux seuls comptent", "ESP décide"], 0, "Minimum des contraintes.");
  Q("essieux", "Ensemble 3 essieux total masse", ["Souvent 26 t maxi", "38 t", "44 t", "40 t"], 0, "Peu d'essieux = masse modérée.");
  Q("essieux", "2 essieux tracteur + 2 essieux semi = 4 ess", ["Ensemble 38 t si loi OK", "19 t", "44 t auto", "26 t semi seule"], 0, "Total 4 essieux ensemble.");
  Q("essieux", "5 essieux ensemble sans dossier 44 t", ["40 t plafond courant", "44 t auto", "19 t", "32 t"], 0, "44 t = conditions cumulatives.");
  Q("essieux", "Essieu relève ( relevable ) à vide", ["Réduit charge essieu mais pas pour tricher pesée", "Augmente PTAC carte", "Coupe ABS", "Modifie longueur"], 0, "Économie et usure, pas surcharge.");
  Q("essieux", "Répartition 40 t mal centrée", ["Essieu arrière ou avant peut dépasser limite", "Sans risque", "ESP corrige masse", "AFU compense"], 0, "Centrage chargement indispensable.");
  Q("essieux", "Contrôle essieu pont-bascule", ["Chaque essieu affiché séparément", "Total seulement", "Sans pesée", "EGR calcule"], 0, "Lire chaque colonne essieu.");
  Q("essieux", "Piège FIMO essieux", ["2=19, 3=26, 4 moteur=32, ens 4=38, 5+=40", "Tous 19 t", "PTAC = essieux seuls", "PTRA sans essieux"], 0, "Tableau essieux à mémoriser.");
  Q("essieux", "Semi 3 essieux PTAC 38 t et dossier 44 t", ["Condition semi pour 44 t", "19 t suffit", "26 t suffit", "Sans lien"], 0, "PTAC semi mini 38 t tridem.");
  Q("essieux", "Charge essieu maxi 44 t ( essieu le plus chargé )", ["12 t ( enseignement FIMO )", "19 t", "15 t", "32 t"], 0, "Plus sévère qu en 40 t.");

  window.QUESTIONS = window.QUESTIONS.concat(extra);
})();
